INSERT INTO english_russian_language (id,england_word, russian_word)
VALUES ( 1, 'here', 'здесь'),
       ( 2, 'away', 'в отъезде'),
       ( 3, 'near', 'рядом'),
       ( 4, 'at home', 'дома'),
       ( 5, 'at school', 'в школе'),
       ( 6, 'on leave', ' в отгуле'),
       ( 7, 'polite', 'вежливый'),
       ( 8, 'kind', 'добрый'),
       ( 9, 'there', 'там'),
       ( 10, 'back', 'назад'),
       ( 11, 'far', 'далеко'),
       ( 12, 'at work', 'на работе'),
       ( 13, 'in Paris', 'в Париже'),
       ( 14, 'on duty', 'на дежурстве'),
       ( 15, 'rude', 'грубый'),
       ( 16, 'cruel', 'жесткий'),
       ( 17, 'short', 'низкий'),
       ( 18, 'fat', 'толстый'),
       ( 19, 'old', 'старый'),
       ( 20, 'poor', 'бедный'),
       ( 21, 'silly', 'глупый'),
       ( 22, 'ill', 'больной'),
       ( 23, 'sad', 'грустный'),
       ( 24, 'lazy', 'ленивый'),
       ( 25, 'tall', 'высокий'),
       ( 26, 'slim', 'тонкий'),
       ( 27, 'young', 'молодой'),
       ( 28, 'rich', 'богатый'),
       ( 29, 'clever', 'умный'),
       ( 30, 'healthy', 'здоровый'),
       ( 31, 'merry', 'веселый'),
       ( 32, 'wise', 'мудрый');

ALTER SEQUENCE erl_seq RESTART WITH 33;